var chatsList = [
  {'Name':'Jui','Title':'voice call','chatImg':'https://images.unsplash.com/photo-1636910043919-c3792c7a0f60?q=80&w=1946&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D','time':'8:58pm'},
  {'Name':'Alex','Title':'Friend','chatImg':'https://source.unsplash.com/random/800x600','time':'12:30pm'},
  {'Name':'Emily','Title':'Co-worker','chatImg':'https://source.unsplash.com/random/800x601','time':'09:45am'},
  {'Name':'David','Title':'Classmate','chatImg':'https://source.unsplash.com/random/800x602','time':'03:20pm'},
  {'Name':'Sophia','Title':'Neighbor','chatImg':'https://source.unsplash.com/random/800x603','time':'06:15pm'},
  {'Name':'Ethan','Title':'Teammate','chatImg':'https://source.unsplash.com/random/800x604','time':'10:55am'},
  {'Name':'Olivia','Title':'Mentor','chatImg':'https://source.unsplash.com/random/800x605','time':'02:40pm'},
  {'Name':'Daniel','Title':'Family','chatImg':'https://source.unsplash.com/random/800x606','time':'05:00pm'},
  {'Name':'Mia','Title':'Roommate','chatImg':'https://source.unsplash.com/random/800x607','time':'11:10am'},
  {'Name':'Logan','Title':'Colleague','chatImg':'https://source.unsplash.com/random/800x608','time':'04:25pm'},
  {'Name':'Ava','Title':'Friend','chatImg':'https://source.unsplash.com/random/800x609','time':'07:30pm'},
  {'Name':'Jackson','Title':'Study buddy','chatImg':'https://source.unsplash.com/random/800x610','time':'01:15pm'},
  {'Name':'Sophie','Title':'Co-worker','chatImg':'https://source.unsplash.com/random/800x611','time':'08:05am'},
  {'Name':'Caleb','Title':'Neighbor','chatImg':'https://source.unsplash.com/random/800x612','time':'03:45pm'},
  {'Name':'Grace','Title':'Teammate','chatImg':'https://source.unsplash.com/random/800x613','time':'09:00am'},
  {'Name':'Liam','Title':'Friend','chatImg':'https://source.unsplash.com/random/800x614','time':'06:50pm'},
  {'Name':'Lily','Title':'Mentor','chatImg':'https://source.unsplash.com/random/800x615','time':'02:10pm'},
  {'Name':'Noah','Title':'Family','chatImg':'https://source.unsplash.com/random/800x616','time':'05:35pm'},
  {'Name':'Chloe','Title':'Roommate','chatImg':'https://source.unsplash.com/random/800x617','time':'11:40am'},
  {'Name':'Aiden','Title':'Colleague','chatImg':'https://source.unsplash.com/random/800x618','time':'04:00pm'},
];
